{
 "title": "prediction_drift",
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "2023-03-31T21:59:59.000Z" },
 "panels": [
  {
   "title": "share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "fare_amount_quarentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_quarentile FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}